### ISSUE TITLE
postProcess内で異常終了することがある

### ISSUE THREAD

**Issue by 7pairs** [7pairs/textlint-plugin-satsuki#12]
下記のようなエラーが発生しました。

```
Unhandled rejection TypeError: Cannot read property '0' of undefined at C:\GitHub\lions-blue\entries\2016\05\05687.txt
    at C:\GitHub\lions-blue\node_modules\textlint-plugin-satsuki\lib\SatsukiProcessor.js:82:42
    at Array.filter (native)
    at postProcess (C:\GitHub\lions-blue\node_modules\textlint-plugin-satsuki\lib\SatsukiProcessor.js:80:51)
    at C:\GitHub\lions-blue\node_modules\textlint\lib\linter\linter-processor.js:70:30
```

**Comment by 7pairs** [comment]
当プラグインを外した状態では下記のようなエラーが発生します。ルールによっては不正な行番号を返すことがあり得るようです。

```
Error: Line number (10) greater than maximum line (9)
    at rangeFromLineNumber (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\atom-linter\lib\index.js:178:11)
    at C:/Users/Administrator/.atom/packages/linter-textlint/lib/index.js:109:25
    at Array.map (native)
    at C:/Users/Administrator/.atom/packages/linter-textlint/lib/index.js:105:25
    at tryCatcher (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:628:18)
    at PromiseArray._resolve (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:564:26)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Administrator\.atom\packages\linter-textlint\node_modules\textlint\node_modules\bluebird\js\release\async.js:17:14)
```

**Comment by 7pairs** [comment]
`postProcess` 内の下記の処理で `ignoreMessage` が `undefined` になる可能性を考慮した修正を入れます。

```javascript
const ignoreMessage = this.ignoreMessages[message.line - 1];
```
